---
name: TRD-Velocity
version: 0.0.3
author:
  - 'Takuya Ichikawa <trd.ichi@gmail.com>'
abstract: "[One line description of module's purpose here]"
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Test::More: 0
  version: 0
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
